{"time":"2025-04-06T21:03:55.6082952+03:00","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"c:\\users\\administrator\\desktop\\di725-github\\di725\\assignment_1\\wandb\\run-20250406_210355-crtarpco\\logs\\debug-core.log"}
{"time":"2025-04-06T21:03:55.7234159+03:00","level":"INFO","msg":"created new stream","id":"crtarpco"}
{"time":"2025-04-06T21:03:55.7234528+03:00","level":"INFO","msg":"stream: started","id":"crtarpco"}
{"time":"2025-04-06T21:03:55.7234528+03:00","level":"INFO","msg":"sender: started","stream_id":"crtarpco"}
{"time":"2025-04-06T21:03:55.7234528+03:00","level":"INFO","msg":"handler: started","stream_id":"crtarpco"}
{"time":"2025-04-06T21:03:55.7234528+03:00","level":"INFO","msg":"writer: Do: started","stream_id":"crtarpco"}
{"time":"2025-04-06T21:03:56.1460906+03:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-04-07T07:41:58.803369+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.11:51282->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2025-04-07T07:42:58.7994042+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.11:51566->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2025-04-07T13:34:29.7446282+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.11:54012->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2025-04-07T14:29:59.7575721+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.11:54411->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2025-04-07T14:35:59.8014879+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.11:54867->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2025-04-07T14:37:14.7857832+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.11:54912->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2025-04-07T14:37:29.7990036+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.11:54929->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2025-04-07T14:38:29.7782323+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.11:54933->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2025-04-07T14:47:48.952046+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.11:54941->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-07T14:47:58.9080503+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trial/sentiment_gpt/crtarpco/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-07T14:48:12.2149283+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-07T14:48:22.2998029+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trial/sentiment_gpt/crtarpco/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-07T14:48:46.6043821+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": context deadline exceeded"}
{"time":"2025-04-07T14:48:48.6494305+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trial/sentiment_gpt/crtarpco/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-07T14:49:26.3761242+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"time":"2025-04-07T14:49:28.3918543+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trial/sentiment_gpt/crtarpco/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-07T14:50:06.1272315+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-07T14:50:08.142462+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trial/sentiment_gpt/crtarpco/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-07T14:50:40.9940147+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trial/sentiment_gpt/crtarpco/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-04-07T14:50:44.239873+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-04-07T14:51:41.0077624+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trial/sentiment_gpt/crtarpco/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-04-07T14:51:44.2477843+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-04-07T14:52:41.0204923+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trial/sentiment_gpt/crtarpco/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-04-07T14:52:44.2532007+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-04-07T21:52:29.8311059+03:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/files/trial/sentiment_gpt/crtarpco/file_stream","body":"\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n"}
{"time":"2025-04-07T22:10:11.4006019+03:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/files/trial/sentiment_gpt/crtarpco/file_stream","body":"\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n"}
{"time":"2025-04-07T22:23:56.1622604+03:00","level":"ERROR","msg":"monitor: error sampling metrics: The parameter is incorrect.\ncould not get CreationDate: The parameter is incorrect.\ncouldn't find pid: 20628"}
{"time":"2025-04-07T22:24:11.159028+03:00","level":"ERROR","msg":"monitor: error sampling metrics: The parameter is incorrect.\ncould not get CreationDate: The parameter is incorrect.\ncouldn't find pid: 20628"}
{"time":"2025-04-07T22:24:26.1619439+03:00","level":"ERROR","msg":"monitor: error sampling metrics: The parameter is incorrect.\ncould not get CreationDate: The parameter is incorrect.\ncouldn't find pid: 20628"}
{"time":"2025-04-07T22:24:41.1600366+03:00","level":"ERROR","msg":"monitor: error sampling metrics: The parameter is incorrect.\ncould not get CreationDate: The parameter is incorrect.\ncouldn't find pid: 20628"}
{"time":"2025-04-07T22:24:56.1603281+03:00","level":"ERROR","msg":"monitor: error sampling metrics: The parameter is incorrect.\ncould not get CreationDate: The parameter is incorrect.\ncouldn't find pid: 20628"}
{"time":"2025-04-07T22:25:11.1590549+03:00","level":"ERROR","msg":"monitor: error sampling metrics: The parameter is incorrect.\ncould not get CreationDate: The parameter is incorrect.\ncouldn't find pid: 20628"}
